name = "resin"
compatibility_date = "2025-06-12"

main = "src/index.ts"

[build]
command = "npm run build"

[env.production]
# Database Configuration
MONGODB_URI=mongodb+srv://bhautikkhunt0393:bhautikkhunt0393@resinadmin.ddio6d8.mongodb.net/ecommerce

# Email Configuration
EMAIL_USER=bhautikkhunt4117@gmail.com
EMAIL_PASS=itde ukag ubdv yskn
EMAIL_FROM=bhautikkhunt4117@gmail.com

# Admin Configuration
ADMIN_EMAIL=admin@modernshop.com
ADMIN_PASSWORD=admin123

# JWT Configuration
JWT_SECRET=your-secret-key

# Server Configuration
NODE_ENV=development
PORT=80
